### PR TITLE
Fix decoding bug

### LINKED ISSUE #63: Malformed request body on application start
- Caused by #60, #62 

### Steps to reproduce

- `$ sbt run`

### Observed

An exception

```
org.http4s.MalformedMessageBodyFailure: Malformed request body: Invalid JSON
	at org.http4s.jawn.JawnInstances$$anonfun$jawnDecoder$1$$anonfun$apply$1.applyOrElse(JawnInstances.scala:16) ~[http4s-jawn_2.11-0.15.6.jar:0.15.6]
	at org.http4s.jawn.JawnInstances$$anonfun$jawnDecoder$1$$anonfun$apply$1.applyOrElse(JawnInstances.scala:14) ~[http4s-jawn_2.11-0.15.6.jar:0.15.6]
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223) ~[scala-library-2.11.8.jar:1.0.0-M1]
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219) ~[scala-library-2.11.8.jar:1.0.0-M1]
	at scalaz.stream.Process$$anonfun$partialAttempt$1.apply(Process.scala:392) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$partialAttempt$1.apply(Process.scala:392) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$attempt$1$$anonfun$apply$22.apply(Process.scala:230) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$attempt$1$$anonfun$apply$22.apply(Process.scala:230) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$attempt$1.apply(Process.scala:230) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$attempt$1.apply(Process.scala:229) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go2$1(Free.scala:134) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go(Free.scala:137) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.run(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.go$1(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.step(Process.scala:97) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$Append.step(Process.scala:641) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:143) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:139) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.flatMap(Process.scala:46) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$Emit.flatMap(Process.scala:592) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.scalaz$Free$$fastFlatMap(Free.scala:72) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$scalaz$Free$$fastFlatMap$1.apply(Free.scala:73) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$scalaz$Free$$fastFlatMap$1.apply(Free.scala:73) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go2$1(Free.scala:134) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go(Free.scala:137) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.run(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.go$1(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.step(Process.scala:97) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$Append.step(Process.scala:641) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.go$3(Process.scala:482) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$go$3$3.apply(Process.scala:490) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$go$3$3.apply(Process.scala:490) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:36) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Task$.Try(Task.scala:403) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:36) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:34) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52) ~[scala-library-2.11.8.jar:1.0.0-M1]
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52) ~[scala-library-2.11.8.jar:1.0.0-M1]
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Future.step(Future.scala:109) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Future.listen(Future.scala:75) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:53) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.scalaz$Free$$fastFlatMap(Free.scala:72) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$resume$1.apply(Free.scala:88) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$resume$1.apply(Free.scala:88) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go2$1(Free.scala:134) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go(Free.scala:137) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.run(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380) [scalaz-concurrent_2.11-7.1.11.jar:na]
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380) [scalaz-concurrent_2.11-7.1.11.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_76]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_76]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_76]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_76]
Caused by: jawn.ParseException: exhausted input
	at jawn.AsyncParser.churn(AsyncParser.scala:234) ~[jawn-parser_2.11-0.10.4.jar:0.10.4]
	at jawn.AsyncParser.finish(AsyncParser.scala:98) ~[jawn-parser_2.11-0.10.4.jar:0.10.4]
	at jawnstreamz.package$$anonfun$parseJson$1$$anonfun$apply$2.apply(package.scala:31) ~[jawn-streamz_2.11-0.10.1.jar:0.10.1]
	at jawnstreamz.package$$anonfun$parseJson$1$$anonfun$apply$2.apply(package.scala:31) ~[jawn-streamz_2.11-0.10.1.jar:0.10.1]
	at scalaz.stream.Process$$anonfun$onComplete$1.apply(Process.scala:338) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$onComplete$1.apply(Process.scala:338) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free$$anonfun$run$1.apply(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go2$1(Free.scala:134) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.go(Free.scala:137) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Free.run(Free.scala:187) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.go$1(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.step(Process.scala:97) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$Append.step(Process.scala:641) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.disconnect(Process.scala:247) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$Append.disconnect(Process.scala:641) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$disconnect$2.apply(Process.scala:249) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$disconnect$2.apply(Process.scala:249) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$suspend$1.apply(Process.scala:1498) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$suspend$1.apply(Process.scala:1497) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.go$1(Process.scala:84) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$class.step(Process.scala:97) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$Append.step(Process.scala:641) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$suspendStep$1.apply(Process.scala:106) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$suspendStep$1.apply(Process.scala:105) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12$$anonfun$apply$13.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.stream.Process$$anonfun$2$$anonfun$apply$12.apply(Process.scala:115) ~[scalaz-stream_2.11-0.8.6.jar:na]
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.Trampoline$$anonfun$delay$1.apply(Free.scala:262) ~[scalaz-core_2.11-7.1.11.jar:na]
	at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56) ~[scalaz-core_2.11-7.1.11.jar:na]
	... 70 common frames omitted
```

### Expected

No exceptions

### PR DESCRIPTION
**Pull request by rexim**
Close #63

### CODE REVIEW

File: src/main/scala/me/rexim/issuestant/github/EtagPolling.scala [hunk 1]
```diff
@@ -1,29 +1,50 @@
...
+  private def pollingIteration(previousItem: Item)(implicit decoder: Decoder[E]): Task[Item] =
+    client.fetch[Item](nextRequest(previousItem)) { (response) =>
+      implicit val http4sDecoder = jsonOf[E]
+
+      if (response.status == Status.Ok) {
+        response.as[E].map { e =>
+          (getETag(response), Some(e))
+        }
+      } else {
+        Task((getETag(response), None))
```
Comment (rexim) [inline src/main/scala/me/rexim/issuestant/github/EtagPolling.scala]: We don't cover this case in UTs: https://coveralls.io/builds/12776098/source?filename=src%2Fmain%2Fscala%2Fme%2Frexim%2Fissuestant%2Fgithub%2FEtagPolling.scala#L47

This is why the coverage dropped a little bit. Covering that case may require significant changes, so creating a separate issue for that.

Comment (rexim) [inline src/main/scala/me/rexim/issuestant/github/EtagPolling.scala]: #67
